server:
  port: 10301
  
spring:
  application:
    name: library-rental
  datasource:
    url: jdbc:mysql://104.197.25.115/rental
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rental
    password: rental

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

